<?php

use \Illuminate\Database\Seeder;
use \Illuminate\Support\Facades\DB;
use \App\HardwareItems;

class HardwareTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('hardware_items')->delete();

        HardwareItems::create(array(
            'name' => 'Laptop 1',
            'type' => 'laptop',
            'model' => 'asus',
            'manufacturer' => 'asus',
            'cost_price' => '700',
            'location' => 'cwtch 1',
            'admin_username' => 'admin',
            'alternate_username' => 'casgliadywerin',
            'inventory_number' => '00001',
            'operating_system' => 'windows 7',
            'status' => 'available',
            'last_update' => '',
            'serial_number' => '123-456-789',
            'insurance' => '',
            'service_level_agreement' => '',
            'active_directory' => '',
            'date_of_purchase' => '',
            'supplier_contact' => '',
            'ip_address' => '',
            'notes' => '',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
        ));

        HardwareItems::create(array(
            'name' => 'Laptop 2',
            'type' => 'laptop',
            'model' => 'asus',
            'manufacturer' => 'asus',
            'cost_price' => '700',
            'location' => 'cwtch 1',
            'admin_username' => 'admin',
            'alternate_username' => 'casgliadywerin',
            'inventory_number' => '00002',
            'operating_system' => 'windows 7',
            'status' => 'available',
            'last_update' => '',
            'serial_number' => '234-456-789',
            'insurance' => '',
            'service_level_agreement' => '',
            'active_directory' => '',
            'date_of_purchase' => '',
            'supplier_contact' => '',
            'ip_address' => '',
            'notes' => '',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
        ));

        HardwareItems::create(array(
            'name' => 'Laptop 3',
            'type' => 'laptop',
            'model' => 'asus',
            'manufacturer' => 'asus',
            'cost_price' => '700',
            'location' => 'cwtch 1',
            'admin_username' => 'admin',
            'alternate_username' => 'casgliadywerin',
            'inventory_number' => '00003',
            'operating_system' => 'windows 7',
            'status' => 'available',
            'last_update' => '',
            'serial_number' => '345-456-789',
            'insurance' => '',
            'service_level_agreement' => '',
            'active_directory' => '',
            'date_of_purchase' => '',
            'supplier_contact' => '',
            'ip_address' => '',
            'notes' => '',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
        ));

        HardwareItems::create(array(
            'name' => 'Laptop 4',
            'type' => 'laptop',
            'model' => 'asus',
            'manufacturer' => 'asus',
            'cost_price' => '700',
            'location' => 'cwtch 1',
            'admin_username' => 'admin',
            'alternate_username' => 'casgliadywerin',
            'inventory_number' => '00004',
            'operating_system' => 'windows 8',
            'status' => 'available',
            'last_update' => '',
            'serial_number' => '567-456-789',
            'insurance' => '',
            'service_level_agreement' => '',
            'active_directory' => '',
            'date_of_purchase' => '',
            'supplier_contact' => '',
            'ip_address' => '',
            'notes' => 'Some extra notes',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
        ));

        HardwareItems::create(array(
            'name' => 'Scanner 1',
            'type' => 'scanner',
            'model' => 'Epson v500',
            'manufacturer' => 'Epson',
            'cost_price' => '',
            'location' => 'cwtch 1',
            'admin_username' => '',
            'alternate_username' => '',
            'inventory_number' => '00005',
            'operating_system' => '',
            'status' => '',
            'last_update' => '',
            'serial_number' => '132-465-987',
            'insurance' => '',
            'service_level_agreement' => '',
            'active_directory' => '',
            'date_of_purchase' => '',
            'supplier_contact' => '',
            'ip_address' => '',
            'notes' => '',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
        ));

        HardwareItems::create(array(
            'name' => 'Scanner 2',
            'type' => 'scanner',
            'model' => 'Epson v500',
            'manufacturer' => 'Epson',
            'cost_price' => '',
            'location' => 'cwtch 1',
            'admin_username' => '',
            'alternate_username' => '',
            'inventory_number' => '00006',
            'operating_system' => '',
            'status' => '',
            'last_update' => '',
            'serial_number' => '932-465-987',
            'insurance' => '',
            'service_level_agreement' => '',
            'active_directory' => '',
            'date_of_purchase' => '',
            'supplier_contact' => '',
            'ip_address' => '',
            'notes' => '',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
        ));

        HardwareItems::create(array(
            'name' => 'Scanner 3',
            'type' => 'scanner',
            'model' => 'Epson v500',
            'manufacturer' => 'Epson',
            'cost_price' => '',
            'location' => 'cwtch 1',
            'admin_username' => '',
            'alternate_username' => '',
            'inventory_number' => '00006',
            'operating_system' => '',
            'status' => '',
            'last_update' => '',
            'serial_number' => '132-814-487',
            'insurance' => '',
            'service_level_agreement' => '',
            'active_directory' => '',
            'date_of_purchase' => '',
            'supplier_contact' => '',
            'ip_address' => '',
            'notes' => '',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
        ));

        HardwareItems::create(array(
            'name' => 'Scanner 4',
            'type' => 'scanner',
            'model' => 'Epson v500',
            'manufacturer' => 'Epson',
            'cost_price' => '',
            'location' => 'cwtch 1',
            'admin_username' => '',
            'alternate_username' => '',
            'inventory_number' => '00007',
            'operating_system' => '',
            'status' => '',
            'last_update' => '',
            'serial_number' => '764-618-341',
            'insurance' => '',
            'service_level_agreement' => '',
            'active_directory' => '',
            'date_of_purchase' => '',
            'supplier_contact' => '',
            'ip_address' => '',
            'notes' => '',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
        ));

        HardwareItems::create(array(
            'name' => 'Peli case 1',
            'type' => 'case',
            'model' => 'Peli Storm im2620',
            'manufacturer' => 'peli',
            'cost_price' => '',
            'location' => '',
            'admin_username' => '',
            'alternate_username' => '',
            'inventory_number' => '00008',
            'operating_system' => '',
            'status' => '',
            'last_update' => '',
            'serial_number' => '473-948-322',
            'insurance' => '',
            'service_level_agreement' => '',
            'active_directory' => '',
            'date_of_purchase' => '',
            'supplier_contact' => '',
            'ip_address' => '',
            'notes' => '',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
        ));

        HardwareItems::create(array(
            'name' => 'Peli case 2',
            'type' => 'case',
            'model' => 'Peli Storm im2620',
            'manufacturer' => 'peli',
            'cost_price' => '',
            'location' => '',
            'admin_username' => '',
            'alternate_username' => '',
            'inventory_number' => '00009',
            'operating_system' => '',
            'status' => '',
            'last_update' => '',
            'serial_number' => '779-225-322',
            'insurance' => '',
            'service_level_agreement' => '',
            'active_directory' => '',
            'date_of_purchase' => '',
            'supplier_contact' => '',
            'ip_address' => '',
            'notes' => '',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
        ));

        HardwareItems::create(array(
            'name' => 'Peli case 3',
            'type' => 'case',
            'model' => 'Peli Storm im2620',
            'manufacturer' => 'peli',
            'cost_price' => '',
            'location' => '',
            'admin_username' => '',
            'alternate_username' => '',
            'inventory_number' => '00010',
            'operating_system' => '',
            'status' => '',
            'last_update' => '',
            'serial_number' => '111-948-844',
            'insurance' => '',
            'service_level_agreement' => '',
            'active_directory' => '',
            'date_of_purchase' => '',
            'supplier_contact' => '',
            'ip_address' => '',
            'notes' => '',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
        ));

        HardwareItems::create(array(
            'name' => 'Peli case 4',
            'type' => 'case',
            'model' => 'Peli Storm im2620',
            'manufacturer' => 'peli',
            'cost_price' => '',
            'location' => '',
            'admin_username' => '',
            'alternate_username' => '',
            'inventory_number' => '00011',
            'operating_system' => '',
            'status' => '',
            'last_update' => '',
            'serial_number' => '111-222-654',
            'insurance' => '',
            'service_level_agreement' => '',
            'active_directory' => '',
            'date_of_purchase' => '',
            'supplier_contact' => '',
            'ip_address' => '',
            'notes' => '',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
        ));

        HardwareItems::create(array(
            'name' => 'Canon EOS 5D Mark III',
            'type' => 'camera',
            'model' => 'Canon EOS 5D Mark III',
            'manufacturer' => 'Canon',
            'cost_price' => '',
            'location' => '',
            'admin_username' => '',
            'alternate_username' => '',
            'inventory_number' => '00012',
            'operating_system' => '',
            'status' => '',
            'last_update' => '',
            'serial_number' => '262-745-964',
            'insurance' => '',
            'service_level_agreement' => '',
            'active_directory' => '',
            'date_of_purchase' => '',
            'supplier_contact' => '',
            'ip_address' => '',
            'notes' => '',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
        ));

        HardwareItems::create(array(
            'name' => 'Laser printer',
            'type' => 'printer',
            'model' => 'Canon',
            'manufacturer' => 'Canon',
            'cost_price' => '',
            'location' => '',
            'admin_username' => '',
            'alternate_username' => '',
            'inventory_number' => '00013',
            'operating_system' => '',
            'status' => '',
            'last_update' => '',
            'serial_number' => '987-487-642',
            'insurance' => '',
            'service_level_agreement' => '',
            'active_directory' => '',
            'date_of_purchase' => '',
            'supplier_contact' => '',
            'ip_address' => '',
            'notes' => '',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
        ));

        HardwareItems::create(array(
            'name' => 'TomTom navigation',
            'type' => 'navigation',
            'model' => 'TomTom',
            'manufacturer' => 'TomTom',
            'cost_price' => '',
            'location' => '',
            'admin_username' => '',
            'alternate_username' => '',
            'inventory_number' => '00014',
            'operating_system' => '',
            'status' => '',
            'last_update' => '',
            'serial_number' => '487-654-651',
            'insurance' => '',
            'service_level_agreement' => '',
            'active_directory' => '',
            'date_of_purchase' => '',
            'supplier_contact' => '',
            'ip_address' => '',
            'notes' => '',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
        ));

        HardwareItems::create(array(
            'name' => 'iPhone 4',
            'type' => 'phone',
            'model' => 'iPhone 4',
            'manufacturer' => 'Apple',
            'cost_price' => '',
            'location' => '',
            'admin_username' => '',
            'alternate_username' => '',
            'inventory_number' => '00015',
            'operating_system' => 'ios 7',
            'status' => '',
            'last_update' => '',
            'serial_number' => '159-753-654',
            'insurance' => '',
            'service_level_agreement' => '',
            'active_directory' => '',
            'date_of_purchase' => '',
            'supplier_contact' => '',
            'ip_address' => '',
            'notes' => '',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
        ));

        HardwareItems::create(array(
            'name' => 'Marantz PMD661 MKII 1',
            'type' => 'audio_recorder',
            'model' => 'Marantz PMD661 MKII',
            'manufacturer' => 'Marantz',
            'cost_price' => '599',
            'location' => '',
            'admin_username' => '',
            'alternate_username' => '',
            'inventory_number' => '00016',
            'operating_system' => '',
            'status' => '',
            'last_update' => '',
            'serial_number' => '149-347-846',
            'insurance' => '',
            'service_level_agreement' => '',
            'active_directory' => '',
            'date_of_purchase' => '',
            'supplier_contact' => '',
            'ip_address' => '',
            'notes' => '',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
        ));

        HardwareItems::create(array(
            'name' => 'Marantz PMD661 MKII 2',
            'type' => 'audio_recorder',
            'model' => 'Marantz PMD661 MKII',
            'manufacturer' => 'Marantz',
            'cost_price' => '599',
            'location' => '',
            'admin_username' => '',
            'alternate_username' => '',
            'inventory_number' => '00017',
            'operating_system' => '',
            'status' => '',
            'last_update' => '',
            'serial_number' => '649-347-147',
            'insurance' => '',
            'service_level_agreement' => '',
            'active_directory' => '',
            'date_of_purchase' => '',
            'supplier_contact' => '',
            'ip_address' => '',
            'notes' => '',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
        ));

        HardwareItems::create(array(
            'name' => 'Professional Dynamic Vocal Microphone',
            'type' => 'audio_recorder',
            'model' => 'YU375',
            'manufacturer' => 'ProSound',
            'cost_price' => '',
            'location' => '',
            'admin_username' => '',
            'alternate_username' => '',
            'inventory_number' => '00018',
            'operating_system' => '',
            'status' => '',
            'last_update' => '',
            'serial_number' => '144-155-178',
            'insurance' => '',
            'service_level_agreement' => '',
            'active_directory' => '',
            'date_of_purchase' => '',
            'supplier_contact' => '',
            'ip_address' => '',
            'notes' => '',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
        ));

        HardwareItems::create(array(
            'name' => 'Professional Dynamic Vocal Microphone',
            'type' => 'audio_recorder',
            'model' => 'YU375',
            'manufacturer' => 'ProSound',
            'cost_price' => '',
            'location' => '',
            'admin_username' => '',
            'alternate_username' => '',
            'inventory_number' => '00019',
            'operating_system' => '',
            'status' => '',
            'last_update' => '',
            'serial_number' => '734-651-981',
            'insurance' => '',
            'service_level_agreement' => '',
            'active_directory' => '',
            'date_of_purchase' => '',
            'supplier_contact' => '',
            'ip_address' => '',
            'notes' => '',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
        ));

        HardwareItems::create(array(
            'name' => 'iPad',
            'type' => 'tablet',
            'model' => 'iPad',
            'manufacturer' => 'Apple',
            'cost_price' => '',
            'location' => '',
            'admin_username' => '',
            'alternate_username' => '',
            'inventory_number' => '00020',
            'operating_system' => '',
            'status' => '',
            'last_update' => '',
            'serial_number' => '761-447-357',
            'insurance' => '',
            'service_level_agreement' => '',
            'active_directory' => '',
            'date_of_purchase' => '',
            'supplier_contact' => '',
            'ip_address' => '',
            'notes' => '',
            'created_at' => new DateTime,
            'updated_at' => new DateTime
        ));
    }
}